name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker gcr.io

      - name: Build and Push Docker image
        run: |
          docker build -t gcr.io/wedding-game-prod-999/wedding-game .
          docker push gcr.io/wedding-game-prod-999/wedding-game

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy wedding-game \
            --image gcr.io/wedding-game-prod-999/wedding-game \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated \
            --set-env-vars NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyCw0lbsV5w7j_JlgQhuXd8cVsrnBvy-aic,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=wedding-game-prod-999.firebaseapp.com,NEXT_PUBLIC_FIREBASE_PROJECT_ID=wedding-game-prod-999,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=wedding-game-prod-999.firebasestorage.app,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=50918202904,NEXT_PUBLIC_FIREBASE_APP_ID=1:50918202904:web:7150dfd24232c7765a2d6d
